/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View.GUI;

import Models.Entity.Entity;
import Models.Entity.Monster;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/**
 *
 * @author Maia
 */
public class CombatFrame extends javax.swing.JFrame
{

    private List<Entity> entities;
    private ArrayList<Models.Entity.Character> characters;
    private ArrayList<Monster> monsters;
    private TargetsPanel targetsPanel;

    public CombatFrame(List<Models.Entity.Character> characters, List<Monster> monsters)
    {
        this.entities = new ArrayList();
        this.characters = new ArrayList(characters);
        this.monsters = new ArrayList(monsters);
        
        for (int i = 0; i < this.characters.size(); i++)
        {
            entities.add(this.characters.get(i));
        }

        for (int i = 0; i < this.monsters.size(); i++)
        {
            entities.add(this.monsters.get(i));
        }

        Collections.sort(entities);
        Collections.reverse(entities);

        initComponents();
        initGUI();
    }

    private void initGUI()
    {
        targetsPanel = new TargetsPanel();
        jPanel1.add(targetsPanel);
        jScrollPane1.setViewportView(targetsPanel);

        for (int i = 0; i < entities.size(); i++)
        {
            targetsPanel.addEntity((Entity) entities.get(i));
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 195, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 196, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(173, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(97, 97, 97))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(104, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
